### ISSUE TITLE
Custom paintings missing from Bibliocraft

### ISSUE THREAD

**Issue by swak** [akanimh/nimhtext#2]
I added a few samples on the branch, the requirement is the image must be a PNG

**Comment by akanimh** [comment]
Hmm, I'm not seeing your branch. Any idea why?

**Comment by swak** [comment]
Sync failed to push local changes. It seems you do not have permission to push your changes to this repository.

**Comment by akanimh** [comment]
Woops, added you as a collaborator.

**Comment by akanimh** [comment]
Merged what you added. Funny stuff
